spring:
  config:
    activate:
      on-profile: local
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_HOST}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        storage_engine: innodb
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show_sql: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog-master.yml
  data:
    redis:
      host: argocd-redis.argocd.svc.cluster.local
      port: 6379
      password: ${REDIS_PASSWORD}


springdoc:
  swagger-ui:
    displayOperationId: true
    enabled: true
    persist-authorization: true

logging:
  config: classpath:logback-spring-local.xml
  slack:
    webhook:
      url: ${LOGGING_SLACK_WEBHOOK_URL}

swagger:
#  url: https://noma.minq.work/
  url: http://localhost:8080/
  description: Local Server

aes:
  key: ${AES_KEY}

jwt:
  access_token_expiration_time: 600 # 10분
  refresh_token_expiration_time: 604800 # 7일
  secret: ${JWT_SECRET}

sha:
  key: ${SHA_KEY}

api:
  key: ${DATA_GO_API_KEY}

naver:
  client_id: ${NAVER_CLIENT_ID}
  client_secret: ${NAVER_CLIENT_SECRET}
