spring:
  config:
    activate:
      on-profile: dev

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB

  main:
    allow-bean-definition-overriding: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_HOST}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 50
      minimum-idle: 10
      connection-timeout: 3000
      idle-timeout: 10000
      max-lifetime: 60000

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        storage_engine: innodb
        format_sql: false
        use_sql_comments: false
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show_sql: false

  liquibase:
    enabled: true
    change-log: classpath:db/changelog-master.yml

  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379
      password: ${REDIS_PASSWORD}

springdoc:
  swagger-ui:
    displayOperationId: true
    enabled: true
    persist-authorization: true

swagger:
  url: https://noma.minq.work/
#  url: http://localhost:8080/
  description: Local Server

aes:
  key: ${AES_KEY}

jwt:
  access_token_expiration_time: 600 # 10분
  refresh_token_expiration_time: 604800 # 7일
  secret: ${JWT_SECRET}

sha:
  key: ${SHA_KEY}

api:
  key: ${DATA_GO_API_KEY}

naver:
  client_id: ${NAVER_CLIENT_ID}
  client_secret: ${NAVER_CLIENT_SECRET}
