apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
images:
  - name: myapp
    newName: docker-repo.minq.work/myapp
    newTag: 49-ecea8ed52e6972abb5d1a1fbd23b1182786399c6
  - name: docker-repo.minq.work/myapp
    newTag: 62-8bcd4906e795d667caa4eaf0c92b6ed06520fee8
