name: CI-CD Auto Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: docker-repo.minq.work/myapp
      DATE_TAG: ${{ github.run_number }}
      IMAGE_TAG: ${{ github.sha }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant permission
        run: chmod +x ./gradlew

      - name: Build and Push Image (via Jib)
        env:
          REGISTRY_USER: ${{ secrets.REGISTRY_USER }}
          REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
        run: |
          ./gradlew clean jib \
            -Djib.to.image=${IMAGE_NAME} \
            -Djib.to.auth.username=${REGISTRY_USER} \
            -Djib.to.auth.password=${REGISTRY_PASSWORD} \
            -Djib.to.tags=main

      - name: Notify Build Info (optional)
        run: |
          echo "âœ… Deployed: ${IMAGE_NAME}"
